import {createApp,h} from 'vue';
import Character from './resources/js/components/chanting/CreatedCharacter.vue';
import {defaultCreator} from './resources/js/lib/creator';
const p=new URLSearchParams(location.search);
const poses=['front','three_quarter','defiant'];
const faces=['harbor','weathered','keen','round'];
const outfits=['mariner','scholar','waistcoat','ritual'];
const hats=['none','watchcap','widebrim','tricorn','hood','antlers'];
const recipe={...defaultCreator,body_type:p.get('body')||'type2',pose:p.get('pose')||'defiant',hair:p.get('hair')||'bald',hat:p.get('hat')||'none',detail:p.get('detail')||'none'};
const rows=p.has('hats')?faces.flatMap(face=>hats.map(hat=>({...recipe,face,hat}))):faces.flatMap(face=>outfits.map(outfit=>({...recipe,face,outfit})));
document.head.insertAdjacentHTML('beforeend',`<style>body{margin:0;background:#181f23;color:#eee;font:14px Georgia}.grid{display:grid;grid-template-columns:repeat(${p.get('cols')||4},1fr);gap:4px}.cell{background:radial-gradient(ellipse at 50% 25%,#53615e,#232e32 65%);border:1px solid #647376}.label{padding:8px;font-size:16px}.portrait{height:${p.get('height')||430}px;position:relative}.mini{width:61px;height:68px;position:absolute;right:8px;bottom:8px;background:#182528;border:1px solid #a39264}.large{height:100%;position:relative}</style>`);
createApp({render(){return h('main',{class:'grid'},rows.map(r=>h('section',{class:'cell'},[h('div',{class:'label'},`${r.body_type} ${r.pose} ${r.face} ${p.has('hats')?r.hat:r.outfit}`),h('div',{class:'portrait'},[h('div',{class:'large'},[h(Character,{recipe:r,mode:'mirror'})]),h('div',{class:'mini'},[h(Character,{recipe:r})])])])));}}).mount('#app');
