<?php

return [
    'presence' => [
        'timeout_seconds' => 45,
        'navigation_grace_seconds' => 5,
        'missed_phases' => 2,
        'prompt_seconds' => 15,
        'abandoned_seconds' => 300,
    ],
    'rules_version' => 'large-gatherings-v1',
    'min_players' => (int) env('GAME_MIN_PLAYERS', 3),
    'max_players' => (int) env('GAME_MAX_PLAYERS', 15),
    'cultists_by_player_count' => [3 => 1, 4 => 1, 5 => 2, 6 => 2, 7 => 3, 8 => 3, 9 => 4, 10 => 4, 11 => 4, 12 => 4, 13 => 5, 14 => 5, 15 => 5],
    'town_roles_min_players' => ['warden' => 5, 'lamplighter' => 7, 'medium' => 8, 'bellkeeper' => 10],
    'cult_roles_min_players' => ['dreamweaver' => 7],
    'illusion_town_roles_min_players' => ['exorcist' => 5, 'lamplighter' => 7, 'oathkeeper' => 8, 'bellkeeper' => 10],
    'illusion_cult_roles_min_players' => ['counterfeiter' => 5, 'dreamweaver' => 7],
    'hard_town_roles_min_players' => ['tracker' => 5, 'exorcist' => 7, 'herbalist' => 8, 'oathkeeper' => 10],
    'hard_cult_roles_min_players' => ['counterfeiter' => 5, 'phantasm' => 7, 'dreamweaver' => 9],
    'role_alignments' => [
        'vigilante' => 'town',
        'oracle' => 'town', 'townsperson' => 'town', 'warden' => 'town', 'lamplighter' => 'town', 'medium' => 'town', 'bellkeeper' => 'town', 'exorcist' => 'town', 'oathkeeper' => 'town', 'tracker' => 'town', 'herbalist' => 'town',
        'veilweaver' => 'cult', 'acolyte' => 'cult', 'dreamweaver' => 'cult', 'phantasm' => 'cult', 'counterfeiter' => 'cult',
    ],
    'tokens_per_player' => 1.2,
    // Large gatherings need four full-team scoring nights before the final vote.
    'ritual_goals_by_player_count' => [3 => 2, 4 => 3, 11 => 16, 12 => 16, 13 => 20, 14 => 20, 15 => 20],
    'small_gathering_max_players' => 4,
    'small_gathering_mission' => ['id' => 'solitary', 'name' => 'A voice below', 'description' => 'Chant each night to advance the ritual by one step. Being investigated does not stop your chant.'],
    'characters' => [
        ['id' => 'mariner', 'name' => 'The Mariner'],
        ['id' => 'botanist', 'name' => 'The Botanist'],
        ['id' => 'lamplighter', 'name' => 'The Lamplighter'],
        ['id' => 'archivist', 'name' => 'The Archivist'],
        ['id' => 'baker', 'name' => 'The Baker'],
        ['id' => 'astronomer', 'name' => 'The Astronomer'],
        ['id' => 'ferryman', 'name' => 'The Ferryman'],
        ['id' => 'musician', 'name' => 'The Musician'],
        ['id' => 'drifter', 'name' => 'The Drifter'],
        ['id' => 'whisperer', 'name' => 'The Whisperer'],
        ['id' => 'smuggler', 'name' => 'The Smuggler'],
        ['id' => 'lookout', 'name' => 'The Lookout'],
        ['id' => 'trickster', 'name' => 'The Trickster'],
        ['id' => 'locksmith', 'name' => 'The Locksmith'],
        ['id' => 'prowler', 'name' => 'The Prowler'],
        ['id' => 'stranger', 'name' => 'The Stranger'],
        ['id' => 'tidecaller', 'name' => 'The Tidecaller'],
        ['id' => 'cartographer', 'name' => 'The Cartographer'],
        ['id' => 'maskmaker', 'name' => 'The Maskmaker'],
        ['id' => 'drowned_regent', 'name' => 'The Drowned Regent'],
        ['id' => 'seasonal_warden', 'name' => 'The Knight'],
        ['id' => 'seasonal_cultist', 'name' => 'The Dark Elf'],
        ['id' => 'seasonal_oathkeeper', 'name' => 'The Paladin'],
    ],
    'seconds' => ['reveal' => 25, 'night' => 45, 'discussion' => 90, 'last_words' => 30, 'voting' => 45],
    'discussion_base_players' => 10,
    'discussion_extra_seconds_per_player' => 10,
    'paranoia_discussion_seconds' => ['early' => 90, 'middle' => 70, 'late' => 50],
    'missions' => [
        'concord' => ['id' => 'concord', 'name' => 'A chorus in the deep', 'description' => 'Every living cultist must chant tonight. If all do, each chant advances the ritual by one step. A lone survivor can chant alone.'],
        'shadows' => ['id' => 'shadows', 'name' => 'Beyond the lantern light', 'description' => 'Each cultist who chants without being investigated tonight advances the ritual by one step.'],
        'patience' => ['id' => 'patience', 'name' => 'The faithful endure', 'description' => 'Each chant advances the ritual by one step if the previous vote did not banish a cultist. The first night counts too.'],
    ],
];
