<?php

return [
    'rules_version' => 'final-ritual-vote-v1',
    'min_players' => (int) env('GAME_MIN_PLAYERS', 3),
    'max_players' => (int) env('GAME_MAX_PLAYERS', 10),
    'cultists_by_player_count' => [3 => 1, 4 => 1, 5 => 2, 6 => 2, 7 => 3, 8 => 3, 9 => 4, 10 => 4],
    'tokens_per_player' => 1.2,
    'ritual_goals_by_player_count' => [3 => 3, 4 => 4],
    'small_gathering_max_players' => 4,
    'small_gathering_mission' => ['id' => 'solitary', 'name' => 'A voice below', 'description' => 'Chant each night to advance the ritual by one step. Being investigated does not stop your chant.'],
    'characters' => [
        ['id' => 'mariner', 'name' => 'The Mariner'],
        ['id' => 'botanist', 'name' => 'The Botanist'],
        ['id' => 'lamplighter', 'name' => 'The Lamplighter'],
        ['id' => 'archivist', 'name' => 'The Archivist'],
        ['id' => 'baker', 'name' => 'The Baker'],
        ['id' => 'astronomer', 'name' => 'The Astronomer'],
        ['id' => 'ferryman', 'name' => 'The Ferryman'],
        ['id' => 'musician', 'name' => 'The Musician'],
        ['id' => 'drifter', 'name' => 'The Drifter'],
        ['id' => 'whisperer', 'name' => 'The Whisperer'],
        ['id' => 'smuggler', 'name' => 'The Smuggler'],
        ['id' => 'lookout', 'name' => 'The Lookout'],
        ['id' => 'trickster', 'name' => 'The Trickster'],
        ['id' => 'locksmith', 'name' => 'The Locksmith'],
        ['id' => 'prowler', 'name' => 'The Prowler'],
        ['id' => 'stranger', 'name' => 'The Stranger'],
    ],
    'seconds' => ['reveal' => 25, 'night' => 45, 'discussion' => 90, 'voting' => 45],
    'missions' => [
        'concord' => ['id' => 'concord', 'name' => 'A chorus in the deep', 'description' => 'Every living cultist must chant tonight. If all do, each chant advances the ritual by one step. A lone survivor can chant alone.'],
        'shadows' => ['id' => 'shadows', 'name' => 'Beyond the lantern light', 'description' => 'Each cultist who chants without being investigated tonight advances the ritual by one step.'],
        'patience' => ['id' => 'patience', 'name' => 'The faithful endure', 'description' => 'Each chant advances the ritual by one step if the previous vote did not banish a cultist. The first night counts too.'],
    ],
];
